Update ktor monorepo to v2.3.12 (#5)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [io.ktor:ktor-server-status-pages](https://togithub.com/ktorio/ktor) |
`2.3.11` -> `2.3.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-status-pages/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-status-pages/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-status-pages/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-status-pages/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[io.ktor:ktor-server-html-builder-jvm](https://togithub.com/ktorio/ktor)
| `2.3.11` -> `2.3.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-html-builder-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-html-builder-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-html-builder-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-html-builder-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-netty-jvm](https://togithub.com/ktorio/ktor) |
`2.3.11` -> `2.3.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-netty-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-netty-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-netty-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-netty-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-config-yaml](https://togithub.com/ktorio/ktor) |
`2.3.11` -> `2.3.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-config-yaml/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-config-yaml/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-config-yaml/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-config-yaml/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [io.ktor:ktor-server-core-jvm](https://togithub.com/ktorio/ktor) |
`2.3.11` -> `2.3.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.ktor:ktor-server-core-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.ktor:ktor-server-core-jvm/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.ktor:ktor-server-core-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.ktor:ktor-server-core-jvm/2.3.11/2.3.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>ktorio/ktor (io.ktor:ktor-server-status-pages)</summary>

### [`v2.3.12`](https://togithub.com/ktorio/ktor/releases/tag/2.3.12)

[Compare
Source](https://togithub.com/ktorio/ktor/compare/2.3.11...2.3.12)

> Published 20 June 2024

##### Bugfixes

- NoSuchMethodError when using coroutines 1.9.0-RC
([KTOR-7054](https://youtrack.jetbrains.com/issue/KTOR-7054))
- Server: Content-Type header for static js, css and svg resources
misses charset
([KTOR-6655](https://youtrack.jetbrains.com/issue/KTOR-6655))
- Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network
([KTOR-7016](https://youtrack.jetbrains.com/issue/KTOR-7016))

##### Improvements

- Update netty to 4.1.111.Final
([KTOR-7094](https://youtrack.jetbrains.com/issue/KTOR-7094))
- Update netty due to CVE-2024-29025
([KTOR-7014](https://youtrack.jetbrains.com/issue/KTOR-7014))
- Update dependency on swagger
([KTOR-7019](https://youtrack.jetbrains.com/issue/KTOR-7019))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View the
[repository job
log](https://developer.mend.io/github/DonRobo/home-former).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy40MzguMCIsInVwZGF0ZWRJblZlciI6IjM3LjQzOC4wIiwidGFyZ2V0QnJhbmNoIjoiZGV2ZWxvcCIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>